# Goodix GXFP5187 SPI (TLS-PSK) driver for libfprint
#
# Copyright (C) 2026 Benjamin Allègre (https://github.com/Sigfrodr)
#
# SPDX-License-Identifier: LGPL-2.1-or-later
# The Goodix sensor sends SPI frames of about 22 kB (the image); spidev caps
# each transfer at "bufsiz" (4096 by default). Raising it is mandatory.
options spidev bufsiz=65536
